# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: hashicorp/packer-plugin-vsphere/build_plugin_binaries
permissions:
  contents: read
on:
  push:
    branches:
    - main
jobs:
  build_darwin:
    defaults:
      run:
        working-directory: ~/go/src/github.com/vmware/packer-plugin-vsphere
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/cimg/go:1.21
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: darwin
        GOARCH: amd64
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: darwin
        GOARCH: arm64
  build_freebsd:
    defaults:
      run:
        working-directory: ~/go/src/github.com/vmware/packer-plugin-vsphere
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/cimg/go:1.21
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: freebsd
        GOARCH: 386
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: freebsd
        GOARCH: amd64
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: freebsd
        GOARCH: arm
  build_linux:
    defaults:
      run:
        working-directory: ~/go/src/github.com/vmware/packer-plugin-vsphere
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/cimg/go:1.21
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: linux
        GOARCH: 386
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: linux
        GOARCH: amd64
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: linux
        GOARCH: arm
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: linux
        GOARCH: arm64
  build_netbsd:
    defaults:
      run:
        working-directory: ~/go/src/github.com/vmware/packer-plugin-vsphere
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/cimg/go:1.21
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: netbsd
        GOARCH: 386
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: netbsd
        GOARCH: amd64
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: netbsd
        GOARCH: arm
  build_openbsd:
    defaults:
      run:
        working-directory: ~/go/src/github.com/vmware/packer-plugin-vsphere
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/cimg/go:1.21
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: openbsd
        GOARCH: 386
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: openbsd
        GOARCH: amd64
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: openbsd
        GOARCH: arm
  build_solaris:
    defaults:
      run:
        working-directory: ~/go/src/github.com/vmware/packer-plugin-vsphere
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/cimg/go:1.21
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: solaris
        GOARCH: amd64
  build_windows:
    defaults:
      run:
        working-directory: ~/go/src/github.com/vmware/packer-plugin-vsphere
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/cimg/go:1.21
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: windows
        GOARCH: 386
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: windows
        GOARCH: amd64
